name: Run tests for OTUS homework

on:
  push:
    branches: kubernetes-*
  pull_request:
    branches: kubernetes-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Checkout repo with tests
      uses: actions/checkout@v2
      with:
        repository: "express42/otus-platform-tests"
        ref: github-actions
        path: "./otus-platform-tests/"

    - name: Run tests
      run: curl https://raw.githubusercontent.com/express42/otus-platform-tests/github-actions/run.sh | bash
